export enum Pages {
  DASHBOARD = 'dashboard',
  WAREHOUSE = 'warehouse',
  REGISTER = 'register',
  REGISTER_STEP_2 = 'register/step-two',
  REGISTER_STEP_3 = 'register/step-three',
  LOGIN = 'login',
  RACK_DETAIL = 'rack/detail',
  HOME = 'home',
  PROFILE = 'my-profile',
  SETTINGS = 'settings',
  ERROR = "error-404",
  RACK = "rack",
  GLOBAL_RACK = "corsia",
  FORGOT_PASSWORD = "forgotten/password",
  USERS = "users",
  USER = "user",
  CREATE = "insert",
  EDIT = "edit",
  RESET_PASSWORD = "noAuth/resetPassword",
  CHANGE_PASSWORD = "change/password",
  MANAGE_ACCOUNT = "manage/account"
}
